var pList = {
    a:["Aa", "Alice", "Apple", "Alice is eating an apple"],
    b:["Bb", "Bike", "Brother", "My Brother Jim is riding a blue bike"],
    c:["Cc", "cakes", "Cici", "Coffee ", "Cici likes coffee and cakes"],
    d:["Dd", "Dad", "Duke", "Door", "Dad is fixing the door with Duke"],
    e:["Ee", "Earring", "Emily", "Emily’s ears wear beautiful earrings"],
    f:["Ff", "Fish ", "Food", "Frank ", "Frank’s favourite food is fish"],
    g:["Gg", "Grandma", "Grandpa", "Grape", "Grandma and grandpa are eating grapes"],
    h:["Hh", "Harry", "Horse", "House", "Harry’s house has a horse"],
    i:["Ii", "Ice cream", "in", "Insect", "An insect is eating an ice cream in the box"],
    j:["Jj", "Jim", "Juice", "Jim enjoys orange juice"],
    k:["Kk", "Kangaroo", "Kid", "Kids like kangaroos"],
    l:["Ll", "Lamp", "Lucy", "Lucy likes lamps"],
    m:["Mm", "mom", "music ", "Mom loves making music"],
    n:["Nn", "Nora", "Number", "Nora likes the number nine"],
    o:["Oo", "Old", "Owl", "The owl on the tree is old"],
    p:["Pp", "Parent", "Park", "Piano", "My parents are playing the piano in the park"],
    q:["Qq", "Queen", "Quilt", "Quietly", "Queen is sleeping in the quilt quietly"],
    r:["Rr", "Raft", "Ride", "Rose can ride a raft"],
    s:["Ss", "Sand", "Sleep", "sunny", "Sunny is sleeping on the sand"],
    t:["Tt", "Tennis", "Twins", "Emily and Alice are twins，they are playing tennis"],
    u:["Uu", "Umbrella", "The umbrella flies up"],
    v:["Vv", "Vegetables", "Vicky", "Vicky loves vegetables"],
    w:["Ww", "Walrus", "Wave", "Walrus is waving at you"],
    x:["Xx", "Max", "Six", "Max is six years old"],
    y:["Yy", "Young", "Yogurt", "Young sisters like yogurt"],
    z:["Zz", "Zebra", "Zoo", "Zebras live in the zoo"],
}


var audioList = {
    a:["03ren_a.mp3", "03ren_a_pic2_apple.mp3", "03ren_a_pic3_alice.mp3", "03ren_a_pic4_juzi.mp3"],
    b:["03ren_b.mp3", "03ren_b_pic2_bike.mp3", "03ren_b_pic3_brotherjim.mp3", "03ren_b_pic4_juzi.mp3"],
    c:["03ren_c.mp3", "03ren_c_pic2_cake.mp3", "03ren_c_pic3_coffee.mp3","03ren_c_pic4_cici.mp3","03ren_c_pic5_juzi.mp3"],
    d:["03ren_d.mp3", "03ren_d_pic2_dog.mp3", "03ren_d_pic3_door.mp3", "03ren_d_pic4_frankdad.mp3", "03ren_d_pic5_juzi.mp3"],
}
