var pList = {
    a:["Aa", "Aa", "Aa", "Aa",],
    b:["Bb", "Bb", "Bb", "Bb",],
    c:["Cc", "Cc", "Cc", "Cc", "Cc",],
    d:["Dd", "Dd", "Dd", "Dd", "Dd",],
    e:["Ee", "Ee", "Ee", "Ee", "Ee",],
    f:["Ff", "Ff ", "Ff ", "Ff ", "Ff ",],
    g:["Gg", "Gg", "Gg", "Gg", "Gg",],
    h:["Hh", "Hh", "Hh", "Hh", "Hh",],
    i:["Ii", "Ii", "Ii", "Ii", "Ii",],
    j:["Jj", "Jj", "Jj", "Jj",],
    k:["Kk", "Kk", "Kk", "Kk",],
    l:["Ll", "Ll", "Ll", "Ll",],
    m:["Mm", "Mm", "Mm", "Mm",],
    n:["Nn", "Nn", "Nn", "Nn",],
    o:["Oo", "Oo", "Oo", "Oo",],
    p:["Pp", "Pp", "Pp", "Pp", "Pp",],
    q:["Qq", "Qq", "Qq", "Qq", "Qq",],
    r:["Rr", "Rr", "Rr", "Rr",],
    s:["Ss", "Ss", "Ss", "Ss", "Ss",],
    t:["Tt", "Tt", "Tt", "Tt",],
    u:["Uu", "Uu", "Uu",],
    v:["Vv", "Vv", "Vv", "Vv",],
    w:["Ww", "Ww", "Ww", "Ww",],
    x:["Xx", "Xx", "Xx", "Xx",],
    y:["Yy", "Yy", "Yy", "Yy",],
    z:["Zz", "Zz", "Zz", "Zz",],
}


var audioList = {
    a:["03ren_a.mp3", "03ren_a_pic2_apple.mp3", "03ren_a_pic3_alice.mp3", "03ren_a_pic4_juzi.mp3"],
    b:["03ren_b.mp3", "03ren_b_pic2_bike.mp3", "03ren_b_pic3_brotherjim.mp3", "03ren_b_pic4_juzi.mp3"],
    c:["03ren_c.mp3", "03ren_c_pic2_cake.mp3", "03ren_c_pic3_coffee.mp3","03ren_c_pic4_cici.mp3","03ren_c_pic5_juzi.mp3"],
    d:["03ren_d.mp3", "03ren_d_pic2_dog.mp3", "03ren_d_pic3_door.mp3", "03ren_d_pic4_frankdad.mp3", "03ren_d_pic5_juzi.mp3"],
}
