var pList = {
    a:["Aa", "alice", "apple", "Alice is eating an apple"],
    b:["Bb", "bike", "brother", "My Brother Jim is riding a blue bike"],
    c:["Cc", "cakes", "cici", "coffee ", "Cici likes coffee and cakes"],
    d:["Dd", "dad", "duke", "door", "Dad is fixing the door with Duke"],
    e:["Ee", "earring", "emily", "Emily’s ears wear beautiful earrings"],
    f:["Ff", "fish ", "food", "frank ", "Frank’s favourite food is fish"],
    g:["Gg", "grandma", "grandpa", "grape", "Grandma and grandpa are eating grapes"],
    h:["Hh", "harry", "horse", "house", "Harry’s house has a horse"],
    i:["Ii", "ice cream", "in", "insect", "An insect is eating an ice cream in the box"],
    j:["Jj", "jim", "juice", "Jim enjoys orange juice"],
    k:["Kk", "kangaroo", "kid", "Kids like kangaroos"],
    l:["Ll", "lamp", "lucy", "Lucy likes lamps"],
    m:["Mm", "mom", "music ", "Mom loves making music"],
    n:["Nn", "nora", "number", "Nora likes the number nine"],
    o:["Oo", "old", "owl", "The owl on the tree is old"],
    p:["Pp", "parent", "park", "piano", "My parents are playing the piano in the park"],
    q:["Qq", "queen", "quilt", "quietly", "Queen is sleeping in the quilt quietly"],
    r:["Rr", "raft", "ride", "Rose can ride a raft"],
    s:["Ss", "sand", "sleep", "sunny", "Sunny is sleeping on the sand"],
    t:["Tt", "tennis", "twins", "Emily and Alice are twins，they are playing tennis"],
    u:["Uu", "umbrella", "The umbrella flies up"],
    v:["Vv", "vegetables", "vicky", "Vicky loves vegetables"],
    w:["Ww", "walrus", "wave", "Walrus is waving at you"],
    x:["Xx", "max", "six", "Max is six years old"],
    y:["Yy", "young", "yogurt", "Young sisters like yogurt"],
    z:["Zz", "zebra", "zoo", "Zebras live in the zoo"],
}


var audioList = {
    a:["03ren_a.mp3", "03ren_a_pic2_apple.mp3", "03ren_a_pic3_alice.mp3", "03ren_a_pic4_juzi.mp3"],
    b:["03ren_b.mp3", "03ren_b_pic2_bike.mp3", "03ren_b_pic3_brotherjim.mp3", "03ren_b_pic4_juzi.mp3"],
    c:["03ren_c.mp3", "03ren_c_pic2_cake.mp3", "03ren_c_pic3_coffee.mp3","03ren_c_pic4_cici.mp3","03ren_c_pic5_juzi.mp3"],
    d:["03ren_d.mp3", "03ren_d_pic2_dog.mp3", "03ren_d_pic3_door.mp3", "03ren_d_pic4_frankdad.mp3", "03ren_d_pic5_juzi.mp3"],
}
